### ISSUE TITLE
nice to have: a 'backwards-map', a column in the matrix where all the categories to which the requirements apply are listed

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/nmfta-rfp_templates#18]

**Comment by BenGardiner** [comment]
this will be satisfied by the way that automatic generation of the shortlists is being constructed by alison

**Comment by HVCSFriend** [comment]
Done. See Column A - Category on the Appendix II - Matrix tab of file Request for Proposals Appendix I, II - Cybersecurity Shortlists and Requirements Matrix.
